### ISSUE TITLE
Bug: Invalid escape sequence

### ISSUE THREAD

**Issue by XXY233** [Flowsqy/ShopChestLangGenerator#1]
Thank you for developing such a handy program! But I have encountered some small problems when using it.

- The `./grawdlew assembleDist` command in the readme seems to be misspelled.
- The exception occurs when I use the `./app` command:
```
F:\Github\workspace\app\bin>app.bat 047c10e1a6ec7f7bcbb4d5c23a7d21f3b6673780
Exception in thread "main" com.google.gson.JsonSyntaxException: com.google.gson.stream.MalformedJsonException: Invalid escape sequence at line 5036 column 60 path $.parsing.quote.escape
        at com.google.gson.internal.Streams.parse(Streams.java:61)
        at com.google.gson.JsonParser.parseReader(JsonParser.java:102)
        at com.google.gson.JsonParser.parseReader(JsonParser.java:70)
        at fr.flowsqy.shopchestlanggenerator.JsonExtractor.extract(JsonExtractor.java:24)
        at fr.flowsqy.shopchestlanggenerator.App.main(App.java:25)
Caused by: com.google.gson.stream.MalformedJsonException: Invalid escape sequence at line 5036 column 60 path $.parsing.quote.escape
        at com.google.gson.stream.JsonReader.syntaxError(JsonReader.java:1659)
        at com.google.gson.stream.JsonReader.readEscapeCharacter(JsonReader.java:1650)
        at com.google.gson.stream.JsonReader.nextQuotedValue(JsonReader.java:1027)
        at com.google.gson.stream.JsonReader.nextString(JsonReader.java:826)
        at com.google.gson.internal.bind.TypeAdapters$28.readTerminal(TypeAdapters.java:747)
        at com.google.gson.internal.bind.TypeAdapters$28.read(TypeAdapters.java:791)
        at com.google.gson.internal.bind.TypeAdapters$28.read(TypeAdapters.java:725)
        at com.google.gson.internal.Streams.parse(Streams.java:49)
        ... 4 more
```
https://resources.download.minecraft.net/04/047c10e1a6ec7f7bcbb4d5c23a7d21f3b6673780
![image](https://github.com/Flowsqy/ShopChestLangGenerator/assets/46647646/c804ffc0-1fbb-4c73-8b48-9e537d4e36af)

**Comment by Flowsqy** [comment]
I fixed the typo in the README, thx
For the error, it's kinda strange. First, it's a Gson (A JSON library provided by google) error. It says that the line is not correctly formatted and specify the line 5036 and the column 60 but the line ends at column 55. Also, it works on both linux and windows for me, I'm unable to reproduce the error. Looks like it works with java 17 and java 19 but may not with older versions (although it should be). What java version are you using ? (you can obtain it with java -version)

**Comment by XXY233** [comment]
I used java8 before, but now I switched to java17.
```
F:\Github\workspace\app\bin>app.bat 047c10e1a6ec7f7bcbb4d5c23a7d21f3b6673780
Exception in thread "main" com.google.gson.JsonSyntaxException: com.google.gson.stream.MalformedJsonException: Invalid escape sequence at line 5036 column 60 path $.parsing.quote.escape
        at com.google.gson.internal.Streams.parse(Streams.java:61)
        at com.google.gson.JsonParser.parseReader(JsonParser.java:102)
        at com.google.gson.JsonParser.parseReader(JsonParser.java:70)
        at fr.flowsqy.shopchestlanggenerator.JsonExtractor.extract(JsonExtractor.java:24)
        at fr.flowsqy.shopchestlanggenerator.App.main(App.java:25)
Caused by: com.google.gson.stream.MalformedJsonException: Invalid escape sequence at line 5036 column 60 path $.parsing.quote.escape
        at com.google.gson.stream.JsonReader.syntaxError(JsonReader.java:1659)
        at com.google.gson.stream.JsonReader.readEscapeCharacter(JsonReader.java:1650)
        at com.google.gson.stream.JsonReader.nextQuotedValue(JsonReader.java:1027)
        at com.google.gson.stream.JsonReader.nextString(JsonReader.java:826)
        at com.google.gson.internal.bind.TypeAdapters$28.readTerminal(TypeAdapters.java:747)
        at com.google.gson.internal.bind.TypeAdapters$28.read(TypeAdapters.java:791)
        at com.google.gson.internal.bind.TypeAdapters$28.read(TypeAdapters.java:725)
        at com.google.gson.internal.Streams.parse(Streams.java:49)
        ... 4 more

F:\Github\workspace\app\bin>java -version
openjdk version "17.0.8" 2023-07-18
OpenJDK Runtime Environment Temurin-17.0.8+7 (build 17.0.8+7)
OpenJDK 64-Bit Server VM Temurin-17.0.8+7 (build 17.0.8+7, mixed mode, sharing)
```

One thing I found out, maybe the program on my computer doesn't read the file using UTF-8 encoding? The correct encoding of the file is UTF-8. But if I use vscode to force open the file in GBK encoding, I find that the displayed characters are completely incorrect and column 60 will be found.
![image](https://github.com/Flowsqy/ShopChestLangGenerator/assets/46647646/9aeec1fc-0e59-4bfd-9e23-5c631a85b82b)

**Comment by Flowsqy** [comment]
Yep that was my tough but in my head the default charset of Java was UTF-8. My bad, it's platform dependent. It should be fixed now, let me know. (I will fix ShopChest the same way to avoid any errors. If you have already downloaded the jar, you will need to download it again)

**Comment by XXY233** [comment]
LangGenerator works fine now, I'll start testing ShopChest :)
